import './style.css';
import type { ClassData, IssuedRoster, SessionData } from './types.ts';
import { api, dateTime, escapeHtml, relative, setStatus } from './utils.ts';
import { decryptExport, download, encryptExport, verifySignedCsv } from './crypto.ts';
import { buyUrl, initializeLicense, restoreLicense, type LicenseState } from './license.ts';

const app = document.querySelector<HTMLDivElement>('#app')!;
let license: LicenseState = { unlocked: false };
let pollTimer = 0;

const header = () => `<header><div class="nav"><a class="brand" href="/" aria-label="Privacy Class Check-in home"><i class="brand-mark" aria-hidden="true"></i><span>Privacy Class Check-in</span></a><nav aria-label="Main navigation"><ul><li><a href="/#check-in">Check in</a></li><li><a href="/#teacher">Teacher</a></li><li><a href="/privacy">Privacy</a></li></ul></nav></div></header><div id="offline" class="offline" role="status" hidden>You’re offline. Existing notes remain visible, but check-ins need a connection.</div>`;
const footer = () => `<footer><div class="foot"><span>Made for small classes, not surveillance. Botanical artwork is AI-assisted and original.</span><ul><li><a href="/open-export">Open export</a></li><li><a href="/privacy">Privacy</a></li><li><a href="/terms">Terms</a></li><li><a href="https://github.com/B-Divyesh/sf-privacy-class-checkin">Source</a></li></ul></div></footer><div id="global-status" class="status-live" role="status" aria-live="polite"></div>`;
const layout = (main: string) => `${header()}<main id="main">${main}</main>${footer()}`;

function bindNetwork() {
  const update = () => { const el=document.querySelector<HTMLElement>('#offline'); if(el) el.hidden=navigator.onLine; };
  addEventListener('online',update); addEventListener('offline',update); update();
}

function landing() {
  document.title='Privacy Class Check-in — attendance without surveillance';
  app.innerHTML=layout(`
    <section class="shell hero">
      <div><div class="eyebrow">A smaller claim, by design</div><h1>Know who checked in.<br>Nothing more.</h1><p class="lede">A two-minute classroom attendance signal using rotating codes and pseudonymous roster tokens—without location, biometrics, accounts, or background tracking.</p>
        <div class="hero-actions"><a class="btn" href="#check-in">Enter class code</a><a class="btn secondary" href="#teacher">Set up a class</a></div>
        <p class="plain-note"><strong>Honest limit:</strong> a check-in shows that someone had a token and current code. It does not prove physical presence or identity.</p>
      </div>
      <figure class="hero-plate"><i class="pin" aria-hidden="true"></i><picture><source srcset="/botanical-checkin-hero.webp" type="image/webp"><img src="/botanical-checkin-hero.webp" width="1152" height="768" fetchpriority="high" decoding="async" alt="Pressed fern fronds, seed pods, blank specimen tags, and a green pencil arranged as a botanical field plate"></picture><figcaption>Plate 01 — labels without identities; a record without a trail.</figcaption></figure>
    </section>
    <section id="check-in" class="section"><div class="section-inner"><div class="role-grid"><div><div class="eyebrow">Student check-in</div><h2>Use your private label</h2><p>Your teacher shows a six-digit code. Enter it with the roster token they gave you. No account or device permission is needed.</p></div>
      <form id="checkin-form" class="sheet" novalidate><div class="field"><label for="code">Current session code</label><input class="input" id="code" name="code" inputmode="numeric" autocomplete="one-time-code" pattern="[0-9]{6}" maxlength="6" required aria-describedby="code-help"><small id="code-help">Six digits shown by your teacher. It rotates every 90 seconds.</small></div><div class="field"><label for="token">Your roster token</label><input class="input" id="token" name="token" autocapitalize="none" autocomplete="off" spellcheck="false" required placeholder="fern-A7K2"></div><p id="checkin-error" class="error" role="alert"></p><button class="btn" type="submit">Record my check-in</button></form>
    </div></div></section>
    <section class="section principle"><div class="section-inner"><div><div class="eyebrow">Field note</div><h2>Attendance should not become surveillance.</h2><p>This tool records one intentional signal, at one moment, for one class. It refuses the tempting leap from “checked in” to “identity proven.”</p></div><ul class="not-list"><li>No GPS or geofencing</li><li>No camera, face, or fingerprint</li><li>No student accounts or device fingerprinting</li><li>No continuous tracking</li></ul></div></section>
    <section class="section"><div class="section-inner"><div class="eyebrow">How it works</div><h2>Three marks in the notebook</h2><div class="grid-3"><article class="step"><b>01</b><h3>Issue pseudonymous tokens</h3><p>Use aliases such as “Fern 12,” then hand each learner a unique token. Only a one-way token hash reaches the server.</p></article><article class="step"><b>02</b><h3>Show the rotating code</h3><p>Start a session and display its six digits. The code changes every 90 seconds and expires when you close the session.</p></article><article class="step"><b>03</b><h3>Review, correct, export</h3><p>Use the accessible manual fallback, then download a signed CSV encrypted in your browser with your passphrase.</p></article></div></div></section>
    <section id="teacher" class="section"><div class="section-inner role-grid"><div><div class="eyebrow">Teacher setup</div><h2>Prepare a class field sheet</h2><p>Enter pseudonyms, one per line. Avoid names, emails, student IDs, or anything a stranger could connect to a learner.</p><div class="callout"><strong>Keep the issued tokens safe.</strong> They appear once. We store only hashes, so tokens cannot be recovered from the server.</div></div>
      <form id="class-form" class="sheet" novalidate><div class="field"><label for="class-name">Class label</label><input class="input" id="class-name" name="className" maxlength="80" required placeholder="Tuesday field studies"></div><div class="field"><label for="roster">Pseudonyms, one per line</label><textarea class="input" id="roster" name="roster" required placeholder="Fern 01&#10;Fern 02&#10;Fern 03" aria-describedby="roster-help"></textarea><small id="roster-help">1–60 distinct labels. Use pseudonyms, not real names.</small></div><div class="field"><label for="retention">Delete class data after</label><select class="input" id="retention" name="retentionDays"><option value="7">7 days</option><option value="30" selected>30 days</option><option value="90">90 days</option><option value="365">1 year</option></select></div><p id="class-error" class="error" role="alert"></p><button class="btn" type="submit">Create private class</button></form>
    </div></section>
    <section class="section"><div class="section-inner role-grid"><div><div class="eyebrow">Return to a class</div><h2>Open a saved teacher sheet</h2><p>Your teacher link is stored only on this device. Paste the class ID and teacher key from your saved recovery link when moving devices.</p></div><form id="open-form" class="sheet"><div class="field"><label for="open-id">Class ID</label><input class="input" id="open-id" required autocomplete="off"></div><div class="field"><label for="open-key">Teacher key</label><input class="input" id="open-key" required autocomplete="off"></div><p id="open-error" class="error" role="alert"></p><button class="btn" type="submit">Open teacher sheet</button></form></div></section>
    <section class="section"><div class="section-inner narrow"><div class="eyebrow">One-time Field kit</div><h2>Print-ready classroom extras</h2><p>The free tool includes the complete check-in, manual correction, retention controls, and encrypted signed export. A <strong>$29 one-time purchase</strong> unlocks printable specimen-style token cards and future convenience templates—never accessibility or core data access.</p>${licensePanel()}</div></section>`);
  bindLanding();
}

function licensePanel() {
  if(license.unlocked) return `<div class="license-box"><h3>Field kit unlocked</h3><p>Your license is active on this device. Printable cards appear when a class has locally saved tokens.</p></div>`;
  return `<div class="license-box"><h3>Field kit · $29 once</h3><p>No subscription or per-student fee. Sociobot/Dodo is the merchant of record; refunds are handled there and revoke the license.</p>${license.notice?`<p class="error">${escapeHtml(license.notice)}</p>`:''}<div class="toolbar"><a class="btn" href="${buyUrl}">Buy the Field kit</a></div><details><summary>Have a license? Restore it</summary><form id="license-form" class="toolbar"><div class="field"><label for="license-token">License token</label><input id="license-token" class="input" autocomplete="off" required></div><button class="btn secondary" type="submit">Verify license</button></form></details><p class="plain-note">By purchasing, you agree to the <a href="/terms">terms</a>. See how license data is handled in our <a href="/privacy">privacy notice</a>.</p></div>`;
}

function bindLanding() {
  const checkin=document.querySelector<HTMLFormElement>('#checkin-form')!;
  checkin.addEventListener('submit',async e=>{e.preventDefault(); const error=document.querySelector('#checkin-error')!;error.textContent=''; const button=checkin.querySelector('button')!;button.disabled=true;button.textContent='Recording…';try{const form=new FormData(checkin);const result=await api<{alias:string,status:string,recorded:boolean}>('/api/checkins',{method:'POST',body:JSON.stringify({code:form.get('code'),token:form.get('token')})});checkin.innerHTML=`<div class="success" role="status"><strong>${result.recorded?'Check-in recorded.':'Already checked in.'}</strong><br>${escapeHtml(result.alias)} is marked ${escapeHtml(result.status)}.</div><button class="btn secondary" type="button" id="another">Check in another token</button>`;document.querySelector('#another')?.addEventListener('click',landing);}catch(err){error.textContent=(err as Error).message;button.disabled=false;button.textContent='Record my check-in';}});
  const form=document.querySelector<HTMLFormElement>('#class-form')!;
  form.addEventListener('submit',async e=>{e.preventDefault();const error=document.querySelector('#class-error')!;error.textContent='';const button=form.querySelector('button')!;button.disabled=true;button.textContent='Preparing tokens…';try{const data=new FormData(form);const roster=String(data.get('roster')).split(/\r?\n/).map(s=>s.trim()).filter(Boolean);const created=await api<{classId:string;teacherKey:string;className:string;roster:IssuedRoster[]}>('/api/classes',{method:'POST',body:JSON.stringify({className:data.get('className'),roster,retentionDays:Number(data.get('retentionDays'))})});localStorage.setItem(`pcc:key:${created.classId}`,created.teacherKey);localStorage.setItem(`pcc:tokens:${created.classId}`,JSON.stringify(created.roster));location.href=`/?class=${encodeURIComponent(created.classId)}&new=1`;}catch(err){error.textContent=(err as Error).message;button.disabled=false;button.textContent='Create private class';}});
  const open=document.querySelector<HTMLFormElement>('#open-form')!;open.addEventListener('submit',e=>{e.preventDefault();const id=(document.querySelector<HTMLInputElement>('#open-id')!.value).trim();const key=(document.querySelector<HTMLInputElement>('#open-key')!.value).trim();if(!id||!key){document.querySelector('#open-error')!.textContent='Enter both values from the recovery link.';return;}localStorage.setItem(`pcc:key:${id}`,key);location.href=`/?class=${encodeURIComponent(id)}`;});
  document.querySelector<HTMLFormElement>('#license-form')?.addEventListener('submit',e=>{e.preventDefault();try{restoreLicense(document.querySelector<HTMLInputElement>('#license-token')!.value);location.reload();}catch(err){setStatus((err as Error).message,'bad');}});
}

async function teacherPage(classId: string) {
  const params=new URLSearchParams(location.search);const returnedKey=params.get('key');if(returnedKey){localStorage.setItem(`pcc:key:${classId}`,returnedKey);params.delete('key');history.replaceState({},'',`/?${params}`);}
  const key=localStorage.getItem(`pcc:key:${classId}`)||'';
  if(!key){teacherKeyPrompt(classId);return;}
  document.title='Teacher sheet — Privacy Class Check-in';
  app.innerHTML=layout(`<div class="shell"><p role="status">Opening the teacher field sheet…</p></div>`);bindNetwork();
  try {
    const data=await api<ClassData>(`/api/classes/${classId}`,{headers:{'x-teacher-key':key}});
    const requested=params.get('session');const active=data.sessions.find(s=>!s.closedAt&&s.endsAt>Date.now()/1000);const sessionId=requested||active?.id||data.sessions[0]?.id;
    renderTeacher(data,key,sessionId,params.get('new')==='1');
  } catch(err) { app.innerHTML=layout(`<div class="shell narrow"><div class="sheet"><div class="eyebrow">Teacher access</div><h1 class="page-title">Couldn’t open this class</h1><p class="error">${escapeHtml((err as Error).message)}</p><p>Check the recovery link, or clear the saved key and enter it again.</p><div class="toolbar"><button class="btn" id="retry-key">Enter teacher key</button><a class="btn secondary" href="/">Return home</a></div></div></div>`);document.querySelector('#retry-key')?.addEventListener('click',()=>{localStorage.removeItem(`pcc:key:${classId}`);teacherKeyPrompt(classId);}); }
}

function teacherKeyPrompt(classId:string){document.title='Teacher access — Privacy Class Check-in';app.innerHTML=layout(`<div class="shell narrow"><form class="sheet" id="key-form"><div class="eyebrow">Teacher access</div><h1 class="page-title">Enter the teacher key</h1><p>This secret was in your recovery link. It stays on this device.</p><div class="field"><label for="teacher-key">Teacher key</label><input class="input" id="teacher-key" required autocomplete="off"></div><p class="error" id="key-error"></p><button class="btn">Open class</button></form></div>`);document.querySelector<HTMLFormElement>('#key-form')!.addEventListener('submit',e=>{e.preventDefault();const key=document.querySelector<HTMLInputElement>('#teacher-key')!.value.trim();if(!key){document.querySelector('#key-error')!.textContent='Enter the key from the recovery link.';return;}localStorage.setItem(`pcc:key:${classId}`,key);teacherPage(classId);});bindNetwork();}

function renderTeacher(data:ClassData,key:string,sessionId?:string,isNew=false){
  clearInterval(pollTimer);const tokens=readTokens(data.id);const recovery=`${location.origin}/?class=${data.id}&key=${key}`;
  app.innerHTML=layout(`<div class="shell"><div class="eyebrow">Teacher field sheet</div><h1 class="page-title">${escapeHtml(data.name)}</h1><p class="lede">${data.roster.length} pseudonymous roster entries · automatic deletion after ${data.retentionDays} days</p>
    ${isNew?`<div class="success"><strong>Your class is ready.</strong> Save the recovery link and issue each token once.</div>`:''}
    <details ${isNew?'open':''} class="sheet"><summary><strong>Recovery link and issued tokens</strong></summary><div class="field"><label for="recovery">Private teacher recovery link</label><input class="input" id="recovery" readonly value="${escapeHtml(recovery)}"><small>Anyone with this link can manage the class. Store it like a password.</small></div><div class="toolbar"><button class="btn secondary" id="copy-recovery">Copy recovery link</button>${tokens.length?`<button class="btn quiet" id="download-tokens">Download token list</button>`:''}</div>${tokens.length?tokenCards(tokens):`<p class="callout">Tokens are not on this device. They cannot be recovered because the server stores only hashes.</p>`}${tokens.length&&license.unlocked?`<button class="btn no-print" id="print-cards">Print token cards</button>`:tokens.length?`<p><a href="/#teacher">Field kit</a> unlocks printable cards. The plain token download remains free.</p>`:''}</details>
    <section aria-labelledby="session-title" style="margin-top:48px"><div class="eyebrow">Current observation</div><h2 id="session-title">Session</h2><div id="session-area">${sessionId?'<p role="status">Loading session…</p>':startSessionForm()}</div></section>
    <section aria-labelledby="history-title" style="margin-top:64px"><h2 id="history-title">Recent sessions</h2>${historyList(data)}</section>
    <section class="danger-zone"><h2>Delete retained data</h2><p>Immediately remove this class, roster hashes, sessions, and check-ins. This cannot be undone.</p><button class="btn danger" id="delete-class">Delete this class…</button></section></div>`);
  bindNetwork();bindTeacherBase(data,key);if(sessionId)loadSession(data,key,sessionId);else bindStart(data,key);
}

function tokenCards(tokens:IssuedRoster[]){return `<div class="token-grid print-only" aria-label="Printable roster tokens">${tokens.map(t=>`<div class="token-card"><b>${escapeHtml(t.alias)}</b><code>${escapeHtml(t.token)}</code><small>Keep private · ${escapeHtml(location.host)}</small></div>`).join('')}</div>`;}
function readTokens(id:string):IssuedRoster[]{try{return JSON.parse(localStorage.getItem(`pcc:tokens:${id}`)||'[]')}catch{return[]}}
function historyList(data:ClassData){if(!data.sessions.length)return '<div class="empty">No sessions yet. Start one above when class begins.</div>';return `<ul>${data.sessions.map(s=>`<li><a href="/?class=${data.id}&session=${s.id}">${dateTime(s.startedAt)}</a> — ${s.closedAt?'closed':s.endsAt>Date.now()/1000?'active':'ended'}</li>`).join('')}</ul>`;}
function startSessionForm(){return `<form id="start-form" class="sheet narrow"><div class="form-row"><div class="field"><label for="late">Mark late after</label><select id="late" name="lateAfterMinutes" class="input"><option value="5">5 minutes</option><option value="10" selected>10 minutes</option><option value="15">15 minutes</option><option value="30">30 minutes</option></select></div><div class="field"><label for="duration">End session after</label><select id="duration" name="durationMinutes" class="input"><option value="30">30 minutes</option><option value="60" selected>1 hour</option><option value="120">2 hours</option><option value="240">4 hours</option></select></div></div><p class="error" id="start-error"></p><button class="btn" type="submit">Start rotating code</button></form>`;}

function bindTeacherBase(data:ClassData,key:string){
  document.querySelector('#copy-recovery')?.addEventListener('click',async()=>{await navigator.clipboard.writeText((document.querySelector<HTMLInputElement>('#recovery')!).value);setStatus('Recovery link copied.','good');});
  document.querySelector('#download-tokens')?.addEventListener('click',()=>{const rows=readTokens(data.id).map(t=>`${JSON.stringify(t.alias)},${JSON.stringify(t.token)}`).join('\r\n');download(new Blob([`pseudonym,token\r\n${rows}\r\n`],{type:'text/csv'}),`${data.name.replace(/[^a-z0-9]+/gi,'-')}-tokens.csv`);});
  document.querySelector('#print-cards')?.addEventListener('click',()=>window.print());
  document.querySelector('#delete-class')?.addEventListener('click',async()=>{if(!confirm(`Permanently delete “${data.name}” and every check-in? This cannot be undone.`))return;try{await api(`/api/classes/${data.id}`,{method:'DELETE',headers:{'x-teacher-key':key}});localStorage.removeItem(`pcc:key:${data.id}`);localStorage.removeItem(`pcc:tokens:${data.id}`);location.href='/';}catch(err){setStatus((err as Error).message,'bad');}});
}
function bindStart(data:ClassData,key:string){document.querySelector<HTMLFormElement>('#start-form')?.addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget as HTMLFormElement;const error=form.querySelector<HTMLElement>('#start-error')!;error.textContent='';const button=form.querySelector('button')!;button.disabled=true;button.textContent='Starting…';try{const values=new FormData(form);const result=await api<{sessionId:string}>(`/api/classes/${data.id}/sessions`,{method:'POST',headers:{'x-teacher-key':key},body:JSON.stringify({lateAfterMinutes:Number(values.get('lateAfterMinutes')),durationMinutes:Number(values.get('durationMinutes'))})});history.replaceState({},'',`/?class=${data.id}&session=${result.sessionId}`);loadSession(data,key,result.sessionId);}catch(err){error.textContent=(err as Error).message;button.disabled=false;button.textContent='Start rotating code';}});}

async function loadSession(data:ClassData,key:string,sessionId:string){
  try{const session=await api<SessionData>(`/api/classes/${data.id}/sessions/${sessionId}`,{headers:{'x-teacher-key':key}});renderSession(data,key,session);if(session.active){clearInterval(pollTimer);pollTimer=window.setInterval(()=>refreshSession(data,key,sessionId),10_000);}}
  catch(err){document.querySelector('#session-area')!.innerHTML=`<div class="callout"><strong>Could not load session.</strong><br>${escapeHtml((err as Error).message)}</div>${startSessionForm()}`;bindStart(data,key);}
}
async function refreshSession(data:ClassData,key:string,id:string){try{const session=await api<SessionData>(`/api/classes/${data.id}/sessions/${id}`,{headers:{'x-teacher-key':key}});renderSession(data,key,session);}catch(err){setStatus((err as Error).message,'bad');}}
function renderSession(data:ClassData,key:string,s:SessionData){const area=document.querySelector<HTMLElement>('#session-area');if(!area)return;const counts={present:0,late:0,absent:0};s.roster.forEach(r=>counts[r.status]++);area.innerHTML=`
  ${s.active?`<div class="code-board"><span class="eyebrow">Current student code</span><div class="code" aria-label="Session code ${s.code.split('').join(' ')}">${s.code}</div><p class="code-meta">Rotates in about ${s.codeExpiresIn} seconds · ${relative(s.endsAt)}</p></div>`:`<div class="callout"><strong>Session ${s.closedAt?'closed':'ended'}.</strong> Manual corrections and exports remain available.</div>`}
  <div class="metrics" aria-label="Attendance totals"><div class="metric present"><b>${counts.present}</b><span>Present</span></div><div class="metric late"><b>${counts.late}</b><span>Late</span></div><div class="metric absent"><b>${counts.absent}</b><span>Absent</span></div></div>
  <div class="toolbar no-print">${s.active?'<button class="btn danger" id="close-session">Close session</button>':''}<button class="btn secondary" id="refresh-session">Refresh records</button></div>
  <div class="sheet"><h2>Roster marks</h2><p class="plain-note">Manual changes are labeled in the signed export. Every select works by keyboard.</p><table><thead><tr><th>Pseudonym</th><th>Status</th><th>Recorded</th><th>Method</th></tr></thead><tbody>${s.roster.map(r=>`<tr><td data-label="Pseudonym"><strong>${escapeHtml(r.alias)}</strong></td><td data-label="Status"><label class="visually-hidden" for="status-${r.id}">Status for ${escapeHtml(r.alias)}</label><select id="status-${r.id}" data-roster="${r.id}"><option value="present" ${r.status==='present'?'selected':''}>Present</option><option value="late" ${r.status==='late'?'selected':''}>Late</option><option value="absent" ${r.status==='absent'?'selected':''}>Absent</option></select></td><td data-label="Recorded">${r.checkedAt?dateTime(r.checkedAt):'—'}</td><td data-label="Method">${r.source?escapeHtml(r.source):'—'}</td></tr>`).join('')}</tbody></table></div>
  <div class="sheet" style="margin-top:32px"><h2>Signed attendance export</h2><p>Encryption happens on this device. Your passphrase is never sent or stored. Keep it separately; it cannot be recovered.</p><div class="field"><label for="export-pass">Export passphrase</label><input type="password" class="input" id="export-pass" minlength="8" autocomplete="new-password" aria-describedby="pass-help"><small id="pass-help">At least 8 characters. Required for the recommended encrypted download.</small></div><p id="export-error" class="error" role="alert"></p><div class="toolbar"><button class="btn" id="encrypted-export">Download encrypted CSV</button><button class="btn quiet" id="plain-export">Download unencrypted CSV…</button></div></div>`;
  area.querySelectorAll<HTMLSelectElement>('select[data-roster]').forEach(select=>select.addEventListener('change',async()=>{select.disabled=true;try{await api(`/api/classes/${data.id}/sessions/${s.id}/roster/${select.dataset.roster}`,{method:'PUT',headers:{'x-teacher-key':key},body:JSON.stringify({status:select.value})});setStatus('Manual status saved.','good');await refreshSession(data,key,s.id);}catch(err){setStatus((err as Error).message,'bad');select.disabled=false;}}));
  area.querySelector('#refresh-session')?.addEventListener('click',()=>refreshSession(data,key,s.id));
  area.querySelector('#close-session')?.addEventListener('click',async()=>{if(!confirm('Close this session? The code will stop accepting check-ins.'))return;try{await api(`/api/classes/${data.id}/sessions/${s.id}/close`,{method:'POST',headers:{'x-teacher-key':key},body:'{}'});clearInterval(pollTimer);await refreshSession(data,key,s.id);}catch(err){setStatus((err as Error).message,'bad');}});
  area.querySelector('#encrypted-export')?.addEventListener('click',async()=>{const error=area.querySelector<HTMLElement>('#export-error')!;error.textContent='';try{const csv=await fetchCsv(data.id,s.id,key);const pass=(area.querySelector<HTMLInputElement>('#export-pass')!).value;const encrypted=await encryptExport(csv,pass);download(encrypted,`${safeName(data.name)}-${s.startedAt}.attendance.pcc`);setStatus('Encrypted export downloaded. Keep the passphrase separately.','good');}catch(err){error.textContent=(err as Error).message;}});
  area.querySelector('#plain-export')?.addEventListener('click',async()=>{if(!confirm('Download an unencrypted roster export? Anyone with the file can read it.'))return;try{download(new Blob([await fetchCsv(data.id,s.id,key)],{type:'text/csv'}),`${safeName(data.name)}-${s.startedAt}.csv`);}catch(err){setStatus((err as Error).message,'bad');}});
}
const safeName=(name:string)=>name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'attendance';
async function fetchCsv(classId:string,sessionId:string,key:string){const response=await fetch(`/api/classes/${classId}/sessions/${sessionId}/export`,{headers:{'x-teacher-key':key}});if(!response.ok){let msg='Export failed.';try{msg=(await response.json()).error||msg}catch{}throw new Error(msg)}return response.text();}

function legalPage(kind:'privacy'|'terms'){
  const privacy=`<div class="eyebrow">Plain-language notice</div><h1 class="page-title">Privacy</h1><p class="lede">This check-in is designed to know less.</p><h2>What the service stores</h2><ul><li>A teacher’s class label, pseudonymous roster labels, and one-way hashes of issued roster tokens.</li><li>Session start/end times, present/late marks, manual correction labels, and server timestamps.</li><li>A one-way hash of the private teacher key. The readable key stays on the teacher’s device unless they save it elsewhere.</li></ul><h2>What it does not collect</h2><p>No names are required. There are no student accounts, GPS coordinates, biometrics, camera or microphone access, device fingerprints, advertising identifiers, or analytics trackers.</p><h2>Retention and deletion</h2><p>The teacher chooses 7, 30, 90, or 365 days. Expired classes are removed by the service. A teacher can permanently delete a class immediately from its teacher sheet. Browser-stored teacher links and newly issued token lists stay on that browser until the teacher clears them or deletes the class.</p><h2>Exports and licenses</h2><p>Attendance exports are signed by the server and, by default, encrypted in the browser using AES-256-GCM. The passphrase never leaves the browser. If you purchase the optional Field kit, a license token is stored locally and sent to Sociobot’s billing API at most once per day for verification. Sociobot/Dodo acts as merchant of record.</p><h2>Contact</h2><p>For privacy or deletion questions, contact <a href="mailto:privacy@sociobot.in">privacy@sociobot.in</a>. Last updated 27 August 2026.</p>`;
  const terms=`<div class="eyebrow">Use agreement</div><h1 class="page-title">Terms</h1><p class="lede">Use Privacy Class Check-in as an attendance aid, not proof of identity or location.</p><h2>Appropriate use</h2><p>Teachers are responsible for choosing non-identifying labels, issuing tokens safely, obtaining any consent required by their school, correcting records, and protecting exports and recovery links. Do not use the service for high-stakes identity verification, examination proctoring, policing, employment, or covert monitoring.</p><h2>No anti-cheating guarantee</h2><p>A learner can share a current code or token. The service intentionally does not add biometrics, location, device identity, or continuous monitoring to prevent that. It records a limited signal, not verified physical presence.</p><h2>Availability and records</h2><p>The service is provided “as is” without a guarantee of uninterrupted availability. Teachers should use the manual fallback when a learner has no working device or connection, and review exports before treating them as official records.</p><h2>Field kit purchase</h2><p>The optional Field kit costs $29 as a one-time purchase and unlocks printable token cards and convenience templates on licensed devices. The core check-in, manual correction, accessible use, deletion, and exports remain free. Sociobot/Dodo is merchant of record and handles checkout and refunds. A refunded purchase revokes its license.</p><h2>Law and changes</h2><p>You retain responsibility for compliance with school policy and applicable privacy law. Material changes will be dated here. Last updated 27 August 2026.</p>`;
  document.title=`${kind==='privacy'?'Privacy':'Terms'} — Privacy Class Check-in`;app.innerHTML=layout(`<div class="shell narrow legal">${kind==='privacy'?privacy:terms}<p><a href="/">← Return to check-in</a></p></div>`);bindNetwork();
}

function openExportPage(){document.title='Open an encrypted export — Privacy Class Check-in';app.innerHTML=layout(`<div class="shell narrow"><div class="eyebrow">Local export tool</div><h1 class="page-title">Open and verify an export</h1><p class="lede">Decrypt a <code>.pcc</code> attendance file or verify a plain signed CSV. The file and passphrase never leave this browser.</p><form class="sheet" id="open-export-form"><div class="field"><label for="export-file">Attendance export</label><input class="input" id="export-file" type="file" accept=".pcc,.csv,application/json,text/csv" required></div><div class="field"><label for="open-pass">Passphrase <span class="plain-note">(encrypted .pcc files only)</span></label><input class="input" id="open-pass" type="password" autocomplete="current-password"></div><p id="open-export-error" class="error" role="alert"></p><button class="btn" type="submit">Open and verify</button></form><div id="verify-result" aria-live="polite"></div><p><a href="/">← Return to check-in</a></p></div>`);bindNetwork();document.querySelector<HTMLFormElement>('#open-export-form')!.addEventListener('submit',async e=>{e.preventDefault();const file=document.querySelector<HTMLInputElement>('#export-file')!.files?.[0];const error=document.querySelector<HTMLElement>('#open-export-error')!;error.textContent='';if(!file){error.textContent='Choose an export file.';return}try{const contents=await file.text();const csv=file.name.endsWith('.pcc')?await decryptExport(contents,document.querySelector<HTMLInputElement>('#open-pass')!.value):contents;const valid=await verifySignedCsv(csv);const result=document.querySelector<HTMLElement>('#verify-result')!;result.innerHTML=`<div class="${valid?'success':'callout'}"><strong>${valid?'Signature verified.':'Signature could not be verified.'}</strong><br>${valid?'This export matches the record produced by its signing key.':'The file may be older, incomplete, or changed. Review it carefully.'}</div><button class="btn secondary" id="save-opened">Download readable CSV</button>`;result.querySelector('#save-opened')?.addEventListener('click',()=>download(new Blob([csv],{type:'text/csv'}),file.name.replace(/\.attendance\.pcc$|\.pcc$/i,'.csv')));}catch(err){error.textContent=(err as Error).message;}});}

async function boot(){if('serviceWorker'in navigator&&location.protocol!=='http:')navigator.serviceWorker.register('/sw.js').catch(()=>{});license=initializeLicense();addEventListener('license-updated',(event)=>{license=(event as CustomEvent<LicenseState>).detail;if(!new URLSearchParams(location.search).has('class')&&location.pathname==='/')landing();},{once:true});const path=location.pathname;if(path==='/privacy'){legalPage('privacy');return}if(path==='/terms'){legalPage('terms');return}if(path==='/open-export'){openExportPage();return}const classId=new URLSearchParams(location.search).get('class');if(classId){teacherPage(classId);return}landing();}
boot().catch(err=>{app.innerHTML=layout(`<div class="shell narrow"><h1 class="page-title">Something went wrong</h1><p class="error">${escapeHtml(err.message)}</p><button class="btn" id="reload">Try again</button></div>`);document.querySelector('#reload')?.addEventListener('click',()=>location.reload());});
